baseURL = "https://vktr.cz/"
#baseURL = "https://vikmstr.github.io/vktr_cz/"
languageCode = "cs-cz"
title = "Viktor Krejčíř"
theme = "blist"

DefaultContentLanguage = "cz"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = "G-W2966WLD08"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[build]
  writeStats = true

[languages]
  [languages.en]
    title = "Viktor Krejcir"
    contentDir = "content/en"
    [languages.en.params]
    introTitle = "Hi and welcome!"
    introSubtitle="There is a lot of pages on the internet. Another one won`t hurt anyone. :) "
    introPhoto = "/images/03.jpg"
  [languages.cz]
    title = "Viktor Krejčíř"
    contentDir = "content/cz"
    [languages.cz.params]
    introTitle = "Ahoj a vítejte!"
    introSubtitle="Na internetu je spousta stránek. Jedna navíc neuškodí :)"
    introPhoto = "/images/03.jpg"  
[params]
  favicon = ""
  site_logo = ""
  description = "Na internetu je spousta stránek. Jedna navíc neuškodí :)"
  facebook = ""
  twitter = "https://twitter.com/VIKTRCZ"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  darkModeToggle="true"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  ascentColor = "bg-blue-50"
#   featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  featured_image = "/images/03.jpg"
  recent_posts_number = 2
  enableSearch = false


  [languages.en.params.homepage.social]
  # Global params xommon for both languages
  title = "(Anti)socials"
  description = "Few likes them, most use them."
  twitter = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/"
  github = "https://github.com/"
  medium = "https://medium.com/"
  reddit = "https://reddit.com/"
  dribbble = "https://dribbble.com/"

 [languages.cz.params.homepage.social]
  # Global params xommon for both languages
  title = "(A)sociální sítě"
  description = "Málokdo je má rád, většina je používá"
  twitter = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/"
  github = "https://github.com/"
  medium = "https://medium.com/"
  reddit = "https://reddit.com/"
  dribbble = "https://dribbble.com/"


  [markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
